name: Build CI

on:
    push:
        branches:
            - latest

    pull_request:
        branches:
            - latest

jobs:
    build:
        name: Build CI
        runs-on: ubuntu-latest
        steps:
            - name: Clone the repository
              uses: actions/checkout@v2

            - name: Start the Docker Compose services
              run: make start

            - name: Install the project's development dependencies
              run: make install

            - name: Build the extension archive
              run: make build
