name: Vulnerability CI

on:
    push:
        branches:
            - latest

    pull_request:
        branches:
            - latest

jobs:
    vulnerability:
        name: Vulnerability CI
        runs-on: ubuntu-latest
        steps:
            - name: Clone the repository
              uses: actions/checkout@v2

            - name: Start the Docker Compose services
              run: make start

            - name: Install the project's development dependencies
              run: make install

            - name: Audit the development packages for vulnerabilities
              run: make audit
